export { default as Landing } from "./Landing/Landing"
export { default as Leaderboard } from "./Leaderboard/Leaderboard"
export { default as Login } from "./Login/Login"
export { default as Play } from "./Play/Play"
export { default as Profile } from "./Profile/Profile"
export { default as Register } from "./Login/Register"